# version: '4.39.0'
services:
  db:
    image: postgres:latest
    platform: linux/amd64
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trip_app_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    # command: bundle exec rails s -b 0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
      - ./public/assets:/app/assets
    environment:
      TZ: Asia/Tokyo
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SELENIUM_DRIVER_URL: http://chrome:4443/wd/hub
      DEV_DB_PASSWORD: password
      PGDATABASE_DEVELOPMENT: trip_app_development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4443:4443
volumes:
  pg_data:
  bundle_data:
  node_modules:
