default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  username: postgres
  password: password
  pool: 5
  host: db
  port: 5432


development:
  <<: *default
  database: <%= ENV["PGDATABASE_DEVELOPMENT"] || "trip_app_development" %>

test:
  <<: *default
  database: <%= ENV["PGDATABASE_TEST"] || "trip_app_test" %>

production:
  <<: *default
  database: <%= ENV["PGDATABASE_PRODUCTION"] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>